const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
const iconSvg = { linkedin: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6.5 8.2H3V21h3.5V8.2ZM4.75 3A2.05 2.05 0 1 0 4.75 7.1 2.05 2.05 0 0 0 4.75 3ZM21 13.6c0-3.8-2-5.6-4.8-5.6-2.2 0-3.2 1.2-3.8 2v-1.8H9V21h3.4v-6.3c0-1.7.3-3.4 2.5-3.4 2.1 0 2.1 2 2.1 3.5V21H21v-7.4Z"/></svg>', whatsapp: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20.5 3.5A11.8 11.8 0 0 0 12.1 0 11.8 11.8 0 0 0 1.7 17.7L0 24l6.5-1.7A11.9 11.9 0 0 0 24 12a11.8 11.8 0 0 0-3.5-8.5ZM12.1 21.8c-1.8 0-3.6-.5-5.1-1.5l-.4-.2-3.8 1 1-3.7-.2-.4a9.8 9.8 0 1 1 8.5 4.8Zm5.4-7.4c-.3-.2-1.8-.9-2.1-1-.3-.1-.5-.2-.7.2-.2.3-.8 1-.9 1.2-.2.2-.3.2-.6.1-1.6-.8-2.7-1.4-3.8-3.2-.3-.5.3-.5.8-1.7.1-.2 0-.4-.1-.6l-.9-2.1c-.2-.5-.5-.4-.7-.4h-.6c-.2 0-.6.1-.9.4-.3.3-1.1 1.1-1.1 2.7s1.1 3.1 1.3 3.3c.2.2 2.2 3.4 5.4 4.8 2 .9 2.7 1 3.7.8.6-.1 1.8-.7 2-1.4.3-.7.3-1.3.2-1.4 0-.3-.2-.4-.5-.5Z"/></svg>', facebook: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M14 8h3V4h-3c-3.3 0-5 2-5 5v3H6v4h3v8h4v-8h3.3l.7-4H13V9c0-.7.3-1 1-1Z"/></svg>', instagram: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 2h10a5 5 0 0 1 5 5v10a5 5 0 0 1-5 5H7a5 5 0 0 1-5-5V7a5 5 0 0 1 5-5Zm0 2a3 3 0 0 0-3 3v10a3 3 0 0 0 3 3h10a3 3 0 0 0 3-3V7a3 3 0 0 0-3-3H7Zm5 3.5A4.5 4.5 0 1 1 12 16.5 4.5 4.5 0 0 1 12 7.5Zm0 2A2.5 2.5 0 1 0 12 14.5 2.5 2.5 0 0 0 12 9.5Zm5.2-3.1a1.05 1.05 0 1 1 0 2.1 1.05 1.05 0 0 1 0-2.1Z"/></svg>' };
let imageBase = ''; let siteTitle = '';
// Text in the database may contain HTML (<br>, <b>, <i>, <a>...). It is inserted as HTML everywhere it is displayed;
// plain() gives the tag-free version for places that can't hold markup (alt text, tooltips, document.title).
function plain(s) { return String(s ?? '').replace(/<br\s*\/?>/gi, ' ').replace(/<[^>]*>/g, '').replace(/\s+/g, ' ').trim() }
function attr(s) { return plain(s).replace(/"/g, '&quot;') }
function img(p) { return p ? (/^https?:\/\//.test(p) ? p : imageBase + p) : '' }
function applySiteChrome(home) { siteTitle = (home.site && home.site.title) || ''; const t = $('#site-title'); if (t && siteTitle) t.innerHTML = siteTitle; commonFooter(home.person) }
async function load() { try { const key = document.body.dataset.page; const index = await (await fetch('/database/database.json')).json(); imageBase = index.imageBase || ''; const dbKey = key === 'my-story' ? 'myStory' : key === 'education-experience' ? 'educationExperience' : key === 'gis-projects' ? 'gisProjects' : key === 'research-publications' ? 'researchPublications' : key; const data = await (await fetch(index[dbKey])).json(); const home = key === 'home' ? data : await (await fetch(index.home)).json(); applySiteChrome(home); render(key, data); bind() } catch (e) { console.error(e); document.body.insertAdjacentHTML('afterbegin', `<div class="load-error">Could not load the page database: ${e.message}</div>`) } }
function socialLinks(socials) { return socials.map(s => `<a href="${s.url}" target="_blank" rel="noreferrer" aria-label="${attr(s.label)}" title="${attr(s.label)}">${iconSvg[s.icon] || s.icon}</a>`).join('') }
function render(key, data) { if (key === 'home') renderHome(data); else renderPage(key, data) }
function renderHome(d) { document.title = plain(`${d.site.title} | ${d.person.name}`); $('#hero-name').innerHTML = d.person.name; $('#hero-role').innerHTML = d.person.title || d.person.intro; document.querySelector('.hero').style.backgroundImage = `url('${img(d.heroImage)}')`; $('#news-list').innerHTML = d.news.map(n => `<li><span class="news-date">${n.date}:</span> ${n.text} ${n.link ? `<a href="${n.link}">${n.label || 'Read more'}</a>` : ''}</li>`).join(''); renderGallery(d.gallery); $('#education-home').innerHTML = d.education.map(row).join('') + `<h3 class="home-subheading">Experience</h3>` + d.experience.map(row).join(''); $('#project-cards').innerHTML = d.projects.map(p => projectCard(p, '/projects/')).join(''); $('#publication-home').innerHTML = d.publications.map(pub).join(''); $('#contact-email').innerHTML = `<a href="mailto:${d.contact.email}">${d.contact.email}</a>`; $('#contact-phone').innerHTML = `<a href="tel:${d.contact.phone.replace(/[^+\d]/g, '')}">${d.contact.phone}</a>`; $('#contact-location').innerHTML = d.contact.location }
function renderGallery(gallery) {
    let i = 0; const main = $('#gallery-featured'), thumbs = $('#gallery-thumbs'), caption = $('#gallery-caption'); if (!main || !thumbs) return; function show(n) { i = (n + gallery.length) % gallery.length; main.src = img(gallery[i].image); main.alt = plain(gallery[i].alt); if (caption) caption.innerHTML = gallery[i].alt || '';[...thumbs.children].forEach((t, idx) => t.classList.toggle('active', idx === i)) }
    thumbs.innerHTML = gallery.map((g, idx) => `<button class="gallery-thumb" type="button" data-i="${idx}"><img loading="lazy" src="${img(g.image)}" alt="${attr(g.alt)}"></button>`).join('');
    thumbs.querySelectorAll('.gallery-thumb').forEach(t => t.addEventListener('click', () => show(+t.dataset.i)));
    const next = $('#gallery-next'); if (next) next.addEventListener('click', () => show(i + 1));
    show(0)
}
function projectCard(p, page) { return `<article class="project-card"><a href="${page}?view=${p.id || 'overview'}">${p.image ? `<img src="${img(p.image)}" alt="${attr(p.title)}">` : `<div class="project-card-noimg">${p.meta || 'Project'}</div>`}<div class="project-card-body"><h3>${p.title}</h3><p>${p.description || p.summary || p.details || ''}</p><small>${p.meta || ''}</small><span class="card-link">View project →</span></div></a></article>` }
function pub(p) { return `<article class="publication-item"><div class="pub-year">${p.year}</div><h3>${p.title}</h3><p>${p.authors}. ${p.status}. ${p.link ? `<a href="${p.link}" ${p.link.startsWith('http') ? 'target="_blank" rel="noreferrer"' : ''}>Read here</a>` : ''}</p></article>` }
function row(x) { return `<article class="timeline-item"><div class="timeline-period">${x.period}</div><div><h3>${x.institution}</h3><p><strong>${x.role}</strong><br>${x.details}</p></div></article>` }
function renderSection(s) { return `${s.heading ? `<h2>${s.heading}</h2>` : ''}${(s.content || []).map(b => b.type === 'image' ? `<figure class="section-image"><img loading="lazy" src="${img(b.image)}" alt="${attr(b.alt)}">${b.alt ? `<figcaption>${b.alt}</figcaption>` : ''}</figure>` : `<p>${b.text}</p>`).join('')}` }
function renderPage(key, d) {
    document.title = plain(`${d.title} | ${siteTitle || 'Portfolio'}`); $('#page-heading').innerHTML = d.heading; const c = $('#page-content'); const view = new URLSearchParams(location.search).get('view'); if (view && view !== 'overview') { const item = findItem(d, view); if (item) { c.innerHTML = detail(item); return } }
    if (key === 'my-story') c.innerHTML = `<div class="prose">${d.intro ? `<p>${d.intro}</p>` : ''}${(d.sections || []).map(renderSection).join('')}</div>`; if (key === 'education-experience') c.innerHTML = `<h2>Education</h2>${d.education.map(row).join('')}<h2>Experience</h2>${d.experience.map(row).join('')}`; if (key === 'gis-projects') c.innerHTML = renderProjectSegments(d); if (key === 'research-publications') c.innerHTML = d.publications.map(pub).join(''); if (key === 'conferences') c.innerHTML = `<div class="conference-cards">${d.items.map(conferenceCard).join('')}</div>`; if (key === 'leadership') c.innerHTML = `<p class="section-lead">${d.intro || ''}</p><div class="leadership-cards">${d.items.map(i => `<article class="info-card"><h3>${i.title}</h3><p>${i.details}</p><a href="?view=${i.id}">View details →</a></article>`).join('')}</div>`;
}
function renderProjectSegments(d) {
    const cats = (d.categories || []).slice(), known = new Set(cats.map(x => x.id));
    // Projects with a missing/unknown category still show up, under a catch-all group.
    if (d.projects.some(p => !known.has(p.category))) cats.push({ id: '__other', label: 'More projects' });
    const groups = cats.map(c => ({ ...c, items: d.projects.filter(p => (c.id === '__other' ? !known.has(p.category) : p.category === c.id)) }));
    const nav = groups.map(g => `<a href="#seg-${g.id}">${g.label}${g.items.length ? ` <span>${g.items.length}</span>` : ''}</a>`).join('');
    const body = groups.map(g => `<section class="project-segment" id="seg-${g.id}"><h2>${g.label}</h2>${g.items.length ? `<div class="project-cards page-projects">${g.items.map(p => projectCard(p, '')).join('')}</div>` : `<p class="segment-empty">Projects coming soon.</p>`}</section>`).join('');
    return `<p class="section-lead">${d.intro}</p><nav class="segment-nav" aria-label="Project sections">${nav}</nav>${body}`
}
function conferenceCard(i) { return `<article class="conference-card"><div class="info-date">${i.date}</div><h3>${i.title}</h3><p>${i.details}</p><a href="?view=${i.id}">View conference →</a></article>` }
function findItem(d, id) { for (const key of ['projects', 'publications', 'items']) { const item = d[key]?.find(x => (x.id || '') === id); if (item) return item } return null }
function detail(i) { const hasSections = Array.isArray(i.sections) && i.sections.length > 0; return `<article class="detail-view"><p class="detail-kicker">${i.year || i.date || i.meta || 'Portfolio detail'}</p><h2>${i.title || i.name}</h2>${i.image ? `<img class="detail-image" src="${img(i.image)}" alt="${attr(i.title)}">` : ''}${hasSections ? `${i.summary ? `<p>${i.summary}</p>` : ''}${i.sections.map(renderSection).join('')}` : `<p>${i.details || i.description || i.authors || ''}</p>`}${i.status ? `<p><strong>${i.status}</strong></p>` : ''}${i.link ? `<a class="detail-link" href="${i.link}" ${i.link.startsWith('http') ? 'target="_blank" rel="noreferrer"' : ''}>Open related link →</a>` : ''}<p class="back-link"><a href="?view=overview">← Back to overview</a></p></article>` }
function commonFooter(person = {}) { if ($('#footer-name')) $('#footer-name').innerHTML = `© ${new Date().getFullYear()} ${person.name || ''}`; const fs = $('#footer-socials'); if (fs && person.socials) fs.innerHTML = socialLinks(person.socials) }
function bind() { const b = $('.menu-button'), n = $('#site-nav'); if (b) b.addEventListener('click', () => { const open = n.classList.toggle('open'); b.setAttribute('aria-expanded', open) }); $$('#site-nav a').forEach(a => a.addEventListener('click', () => n.classList.remove('open'))) }
load();
